### ISSUE TITLE
Library Installation

### ISSUE THREAD

**Issue by danishhusain** [Navigine/react-native-navigine#4]
* What went wrong:
Could not determine the dependencies of task ':react-native-navigine:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':react-native-navigine:debugCompileClasspath'.
   > Could not find com.github.Navigine:Indoor-Navigation-Android-Mobile-SDK-2.0:20231105.
     Required by:
         project :react-native-navigine
         
         
Can Anyone help me ?

**Comment by PavelTychinin** [comment]
Hi, thanks for issue.
We released new sdk version 1.1.3. Can you try it?

**Comment by danishhusain** [comment]
> Hi, thanks for issue.
> We released new sdk version 1.1.3. Can you try it?

Hi,Pavel
I will give my feedback after  try.

**Comment by danishhusain** [comment]
> Hi, thanks for issue. We released new sdk version 1.1.3. Can you try it?

Still I am getting same problem. I want to install  navigine in latest react-native project.
Can you share more way how to use navigine in latest react-native project.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
5 actionable tasks: 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Navigine:Indoor-Navigation-Android-Mobile-SDK-2.0:20231105.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/20231105/Indoor-Navigation-Android-Mobile-SDK-2.0-20231105.pom
       - https://repo.maven.apache.org/maven2/com/github/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/20231105/Indoor-Navigation-Android-Mobile-SDK-2.0-20231105.pom  
       - file:/D:/Navigine/navigine/node_modules/jsc-android/dist/com/github/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/20231105/Indoor-Navigation-Android-Mobile-SDK-2.0-20231105.pom
       - https://dl.google.com/dl/android/maven2/com/github/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/20231105/Indoor-Navigation-Android-Mobile-SDK-2.0-20231105.pom
       - https://www.jitpack.io/com/github/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/20231105/Indoor-Navigation-Android-Mobile-SDK-2.0-20231105.pom
     Required by:
         project :app > project :react-native-navigine

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
info Run CLI with --verbose flag for more details.

**Comment by PavelTychinin** [comment]
Hi. Try version 1.1.5. Clean project and build again

**Comment by danishhusain** [comment]
> Hi. Try version 1.1.5. Clean project and build again

Thanks for support now its working.
