### ISSUE TITLE
Help Needed: Integrate indoor map using Navigine 

### ISSUE THREAD

**Issue by Sivakajan-tech** [Navigine/react-native-navigine#5]
First of all sorry to raise this question in the GitHub issue. I need help integrating indoor navigation and location features into our React Native app using a custom map and Navigine.  Could you point me towards resources on:

1. Handling our custom indoor map (we are planning to create a map refer our department floor-only one) for compatibility with Navigine.
2. Setting up the Navigine SDK within our React Native project.

Thanks!

**Comment by Sivakajan-tech** [comment]
cc:  @PavelTychinin @Sergeev-Denis

**Comment by PavelTychinin** [comment]
Hello Sivakajan,

Thank you for getting in touch with Navigine!
Our team is excited to start working with you on enabling your vision. To get started with system, I suggest reaching to us via info@navigine.com to discuss ways of leveraging Navigine products for your project.

**Comment by Sivakajan-tech** [comment]
Thanks @PavelTychinin
